# Generated by Django 4.2.18 on 2025-02-12 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_shippingaddress_options_profile_unique_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='unique_id',
        ),
    ]
