# Generated by Django 4.2.18 on 2025-03-05 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_customuser_parent_node_customuser_parent_sponsor'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='referral_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
