# Generated by Django 4.2.18 on 2025-01-29 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='unique_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
