# Generated by Django 4.2.18 on 2025-02-12 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser_unique_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shippingaddress',
            options={'verbose_name_plural': 'Shipping Addresses'},
        ),
        migrations.AddField(
            model_name='profile',
            name='unique_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
